---
name: Build and Push Python Docker Image to GCP Container Registry
on:
  push:
    branches: [ main ]

jobs:
  build-push-gcr:
    name: Build and Push Docker Image to GCP Container Registry
    runs-on: ubuntu-latest
    environment: hw-prod
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      IMAGE_NAME: ${{ secrets.GCP_IMAGE_NAME }}
      REPOSITORY_NAME: ${{ secrets.GCP_REPOSITORY_NAME }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GIT_TAG: v0.1.0
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Login to GCP
    - uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: $GCP_SA_KEY
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Get the latest tag
      id: latest-tag
      run: |-
        git fetch --tags
        echo "GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

    - name: Authenticate Docker to GCP Artifact Registry
      run: |-
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:${{ env.GIT_TAG }} .

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:${{ env.GIT_TAG }} us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:${{ env.GIT_TAG }}
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:${{ env.GIT_TAG }}