# Builds the Docker image and then deploys it to Google Cloud's Artifact Registry
name: 🛠️ Build & Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    name: 🛠️ Build & Deploy
    runs-on: ubuntu-latest
    environment: hw-prod
    steps:
      - uses: 'actions/checkout@v4'
        name: 🔽 Checkout
      
      - uses: 'google-github-actions/auth@v2'
        name: 🔑 Google Cloud Auth
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          # Read up on how the `auth` actions works: https://github.com/google-github-actions/auth
          # If you'd rather use identity providers,
          # comment out the `credentials_json` bit and uncomment the following:
          
          # workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          # service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

      - name: Get the latest tag
        id: latest-tag
        run: |-
          git fetch --tags
          echo "GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: 🐋 Build Docker image
        run: docker build -t ${{ secrets.GCP_IMAGE_NAME }}:latest .

      - name: 🐋 Configure Docker for pushing
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      # This deploys under 2 tags. One is `latest` and the other one is the last commit's SHA
      - name: ☁️ Deploy to GCP Artifact Registry
        run: |-
          docker tag ${{ secrets.GCP_IMAGE_NAME }}:latest ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/${{ secrets.GCP_IMAGE_NAME }}:latest
          docker tag ${{ secrets.GCP_IMAGE_NAME }}:latest ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/${{ secrets.GCP_IMAGE_NAME }}:$GIT_TAG
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/${{ secrets.GCP_IMAGE_NAME }}:latest
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/${{ secrets.GCP_IMAGE_NAME }}:$GIT_TAG