---
name: Build and Push Python Docker Image to GCP Container Registry
on:
  push:
    branches: [ main ]

jobs:
  build-push-gcr:
    name: Build and Push Docker Image to GCP Container Registry
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: cloud-deploy-424319
      IMAGE_NAME: lesson-087
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true


    - name: Get the latest tag
      id: latest-tag
      run: |
        git fetch --tags
        echo "GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME:${{ env.GIT_TAG }} .

    - name: Authenticate Docker to GCP Container Registry
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | gcloud auth activate-service-account --key-file=-
        gcloud auth configure-docker --quiet

    - name: Push Docker Image to GCP Container Registry (GCR)
      run: |-
        docker tag $IMAGE_NAME:${{ env.GIT_TAG }} gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ env.GIT_TAG }}
        docker tag $IMAGE_NAME:${{ env.GIT_TAG }} gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ env.GIT_TAG }}
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ env.GIT_TAG }}
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ env.GIT_TAG }}
